"""Add AdvancedInvoice and AdvancedInvoiceItem models

Revision ID: 3d8aee6337ce
Revises: 5f4ad6e967de
Create Date: 2025-07-05 23:21:59.352837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8aee6337ce'
down_revision = '5f4ad6e967de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('include_gst', sa.Boolean(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('use_company', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('your_name', sa.String(length=120), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('client_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advanced_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advanced_invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advanced_invoice_id'], ['advanced_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advanced_invoice_items')
    op.drop_table('advanced_invoices')
    # ### end Alembic commands ###
